RELOAD_ERROR_MESSAGE = "Reload is only allowed when magazine is empty."
SHOOT_ERROR_MESSAGE = "The magazine is empty! Please reload before shooting."
GRENADE_ERROR_MESSAGE = "No more grenade left!"
SHIELD_ERROR_MESSAGE = "No more shield left!"
SHIELD_COOLDOWN_MESSAGE = "Cooldown time for shield! Not allow to activate."
TARGET_VIEW_ERROR_MESSAGE = "Miss! Target not found."
