RELOAD_ERROR_MESSAGE = "Warning! \n\n Unable to reload as you still have ammo"
SHOOT_ERROR_MESSAGE = "Warning! \n\n You are out of ammo"
GRENADE_ERROR_MESSAGE = "Warning! \n\n You are out of grenades"
SHIELD_ERROR_MESSAGE = "Warning! \n\n  You are out of shields"
SHIELD_COOLDOWN_MESSAGE = "Warning! \n\n Shield on cooldown"
TARGET_VIEW_ERROR_MESSAGE = "Miss! \n\n Target not found."
